### ISSUE TITLE
The authorization code methods should always use auth code grant.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/gateway#48]
Right now they'll use whatever grant is specified, or the default. We want these to aaaaalways use the authorization code grant & configuration, because they're silly otherwise!

**Comment by itsjoekent** [comment]
Whoops, ran into this again. Was banging my head for a bit yesterday haha

Edit: For reference here is the temp fix
https://github.com/DoSomething/voting-app/pull/537/files#diff-0c2a511808959453d0add1d6bc4008dfR51

**Comment by itsjoekent** [comment]
(writing debug notes)

when `authorize` calls `getAuthorizationServer` the grant configured is `client_credentials`

```php
    protected function getAuthorizationServer()
    {
        if (! $this->authorizationServer) {
            dd($this->grant);
```
