### ISSUE TITLE
Update league/oauth2-client version.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/gateway#69]
We're currently [pinned on `~1.4`](https://github.com/DoSomething/gateway/blob/c627ea4ebc6e706b0e37d79f5f988484db742599/composer.json#L9), which has issues on PHP 7.1. To allow users to log in on [next.dosomething.org](https://next.dosomething.org), we should update this dependency to the [latest 2.2 release](https://github.com/thephpleague/oauth2-client/releases).

**Comment by DFurnes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) 🐛 As a developer, I want to look into why login/logout isn't working on http://52.3.246.166/campaigns/teens-for-jeans so that users can login/logout. 🐛](https://trello.com/c/AUJ0Dja4/373-3-as-a-developer-i-want-to-look-into-why-login-logout-isn-t-working-on-http-52-3-246-166-campaigns-teens-for-jeans-so-that-users)

**Comment by weerd** [comment]
What was the specific thing that was updated in 2.2 release that fixed the next.dosomething.org issue?

**Comment by DFurnes** [comment]
Ah, yeah! There was [an issue with the RandomLib dependency](https://github.com/ircmaxell/RandomLib/issues/55) that was used by versions lower than 2.x. The more recent versions of `league/oauth2-client` drop that dependency in favor of bumping the required PHP version to 5.6.
